# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
permalink:           pretty

# Setup
title:               Daniel Kelshaw
tagline:             'Engineering Student in Manchester, UK'
description:         'Blog dedicated to data science/machine learning'
url:                 
baseurl:             'https://danielkelshaw.github.io'
paginate:            3

# About/contact
author:
  name:              Daniel Kelshaw
  url:               
  email:             dkelsh.main@gmail.com

# Custom vars
version:             1.0.0
